apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cm-frontend
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - cm.sigmoid.io
      secretName: sigmoid-io-tls-secret
  rules:
    - host: cm.sigmoid.io
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: frontend-cm-frontend
                port:
                  number: 3000
            